---
resources:
  - name: inspect
    type: git
    source:
      uri: https://github.com/dgruber/cf-inspect.git
      branch: master

jobs:
  - name: building
    plan:
      - get: inspect
        trigger: true
      - task: build
        file: inspect/ci/build_inspect.yml
        on_success:
          task: test
          file: inspect/ci/test_inspect.yml
